name: Build and Deploy
on:
  workflow_dispatch:
  push:
    paths: ["src/stories/**"]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
    permissions:
      id-token: write
      pages: write
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [20.x]
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install and Build 🔧
        run: | # Install npm packages and build the Storybook files
          node --version
          npm ci
          npm run build-storybook-gh
      - name: Deploy 🚀
        uses: bitovi/github-actions-storybook-to-github-pages@v1.0.3
        with:
          install_command: npm ci
          build_command: npm run build-storybook-gh
          path: storybook-static
